#!/bin/bash

apt_install_standards() {

    local list_of_packages
    local -a missing_packages
    local -a packages_to_get=(
        'curl'
        'google-chrome-stable'
        'rails3'
        'scala'
        'ruby1.9.3'
        'scala-doc'
        'git'
        'mercurial'
        'python-pip'
        'mysql'
        'emacs24'
        'open-ssh'
    )

    for index in ${!packages_to_get[*]}
    do
        if ! package_installed ${packages_to_get[$index]}; then
            missing_packages=("${missing_packages[@]}" "${packages_to_get[$index]}")
        fi
    done

    if [[ "$missing_packages" ]]; then
        # Convert list to space-delimited string
        list_of_packages=$( printf "%s " "${missing_packages[@]}" )
        echo list_of_packages
        e_header "Installing missing packages"
        exit
        sudo apt-get install -f -y $list_of_packages

        [[ $? ]] && e_success "Done"

    fi

}
