#!/bin/bash

run_pip() {

    local -a desired_pip_packages=(
        'httpie'
        'pygments'
        'pygments-style-solarized'
    )

    for index in ${!desired_pip_packages[*]}
    do
        if pip list | grep "${desired_pip_packages[index]}"; then
            printf "Package already installed: %s" "${desired_pip_packages[index]}"
        else
            printf "Installing missing package: %s" "${desired_pip_packages[index]}"
            sudo pip install ${desired_pip_packages[index]}
        fi
    done

    unset desired_pip_packages

}
