#!/bin/bash


# Allow aliases to be with sudo
# alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# git
alias gts="git status"
alias gtc="git clone"
# Commit all changes, open default editor for commit message
alias gta="git commit -a"
# Allow an empty commit; used *only* to force a Heroku rebuild, if needed.
alias gempty="git commit --allow-empty"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Long form, no user group, color, show hidden files
alias ll="ls -laoG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Find a process with my Usual Flags
alias pgrp="ps ax | grep"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# Fancycat(tm) -- hat-tip @wilto
alias c="pygmentize -O style=solarized -f console256 -g"

# emacs
alias et="emacsclient -t"
alias estart="emacs --daemon"
alias estop="emacsclient -e '(kill-emacs)'"

# Heroku
alias hgo="git push heroku master"
alias hlogs="heroku logs"

# What the hell aliases do I have again?
alias aliases="cat ~/.dotfiles/bash/bash_aliases | c"
