#!/bin/bash


# Allow aliases to be with sudo
# alias sudo="sudo "

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~"
alias -- -="cd -"

# List dir contents aliases
# ref: http://ss64.com/osx/ls.html
# Long form no user group, color
alias l="ls -oG"
# Order by last modified, long form no user group, color
alias lt="ls -toG"
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AGFoh"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AGFoth"

# Find a process with my Usual Flags
alias pgrp="ps ax | grep"

# Concatenate and print content of files (add line numbers)
alias catn="cat -n"

# emacs
alias et="emacsclient -t"

# Fancycat™ -- hat-tip @wilto
alias c="pygmentize -O style=solarized -f console256 -g"

# What the hell aliases do I have again?
alias aliases="cat ~/.bash_aliases | c"

# IP addresses
# alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
# alias localip="ipconfig getifaddr en1"

# Copy my public key to the pasteboard
# alias pubkey="more ~/.ssh/id_rsa.pub | pbcopy | printf '=> Public key copied to pasteboard.\n'"

# Flush DNS cache
# alias flushdns="dscacheutil -flushcache"
